### PR TITLE
Update filter data of ConvTranspose for Fast Style Transfer nchw models.

### LINKED ISSUE #87: Style transfer fails after upgrading to latest webnn-polyfill
Test: https://webmachinelearning.github.io/webnn-samples/style_transfer/
Error: 
Screenshot from 2021-09-07 15-24-53

### PR DESCRIPTION
**Pull request by BruceDai**
According to ONNX **ConvTranspose** op's filter description as following, if we use default 'oihw' filterLayout, we need transpose the original filter data.
  
```spec
ConvTranspose

W: T
The weight tensor that will be used in the convolutions; has size (C x M/group x kH x kW), where C is the number of channels, and kH and kW are the height and width of the kernel, and M is the number of feature maps. For more than 2 dimensions, the weight shape will be (C x M/group x k1 x k2 x ... x kn), where (k1 x k2 x ... x kn) is the dimension of the kernel. The number of channels in the output should be equal to W.shape[1] * group (assuming zero based indices of the shape array)
```

Fix https://github.com/webmachinelearning/webnn-samples/issues/87

@huningxin @Honry PTAL, thanks.

### CODE REVIEW

**Comment by Honry** [comment]
@huningxin, shall we support `iohw` of `filterLayout` in WebNN?

**Comment by huningxin** [comment]
@Honry 

> shall we support `iohw` of `filterLayout` in WebNN?

I think this is a good request from ONNX support perspective. Could you please file an issue to [webnn spec](https://github.com/webmachinelearning/webnn/issues) for wide feedback? Thanks.

**Comment by Honry** [comment]
Sure, I've created issue at https://github.com/webmachinelearning/webnn/issues/212.

**Comment by huningxin** [comment]
Let's land this fix for now. Thanks.

**Comment by BruceDai** [comment]
Since we have supported `convTranspose2d` op on latest WebNN-polyfill,  I think we could still use the original Style Transfer test-data for Style Transfer  example on webnn-samples repo.

@huningxin Please help revert it, thanks.

**Pull request merged**
