### PR TITLE
Add weights files for facial landmark detection sample

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@BruceDai, @huningxin, PTAL, thanks!

**Comment by BruceDai** [comment]
LGTM. Thanks @Honry

**Comment by Honry** [comment]
Hi @anssiko, @huningxin is on vacation, could you help review and merge this PR?

**Review by huningxin — APPROVED** [review]
LGTM, thanks @Honry !

**Pull request merged**
