### PR TITLE
Add weights files for three CNN fp16 models

### PR DESCRIPTION
**Pull request by mingmingtasd**
PTAL, thanks! @Honry

### CODE REVIEW

**Review by Honry — APPROVED** [review]
LGTM, thanks!

**Comment by Honry** [comment]
+@huningxin, I have no permission to merge it.

**Comment by mingmingtasd** [comment]
I plan to support these three fp16 models (mobilenet, resnet, efficientnet) on webnn-samples, because squeezenet 1.0 fp16 model has accuracy issue. @huningxin

**Comment by huningxin** [comment]
Thanks, let me merge it.

**Pull request merged**
