### PR TITLE
Add Super Resolution Model

### PR DESCRIPTION
**Pull request by bbernhar**
Adds `sub_pixel_cnn_2016` super-resolution model.

### CODE REVIEW

**Comment by ibelem** [comment]
Both @anssiko and @huningxin are on vacation. We should have found a backup plan for this.

**Comment by bbernhar** [comment]
@ibelem No problem. I can switch to other tasks until they return, this isn't blocking me.

**Comment by fujunwei** [comment]
Could you please add a readme to explain how the npy files are generated, and the  license of the model? for example https://github.com/webmachinelearning/test-data/tree/main/models/deeplabv3_mnv2_nchw

**Comment by bbernhar** [comment]
@fujunwei Added a README but omitted the instructions since the scripts I used are not mine.

**Comment by fujunwei** [comment]
LGTM, thanks.

**Comment by bbernhar** [comment]
@fujunwei Can you please merge? Thanks!

**Review by huningxin — APPROVED** [review]
LGTM, thanks @bbernhar !

**Pull request merged**
